name: xmshop
version: 1.0.0+1
publish_to: none
description: xmshop
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  flutter_swiper_view: ^1.1.8
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  webview_flutter: ^4.4.2
  flutter_inappwebview: ^5.8.0
  flutter_html: ^3.0.0-beta.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: xmshopIcon
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: miFont
      fonts:
        - asset: assets/fonts/mi_font.ttf
  assets:
    - assets/images/