name: xmshop
version: 1.0.0+1
publish_to: none
description: xmshop
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  flutter_swiper_view: ^1.1.8
  flutter_spinkit: ^5.2.0
  flutter: 
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: xmshopIcon
      fonts:
        - asset: assets/fonts/iconfont.ttf
  assets:
    - assets/images/