import 'package:flutter/material.dart';

class XmshopIcons {
  static const IconData collect =
      IconData(0xe907, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData share =
      IconData(0xe900, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData mine =
      IconData(0xe90d, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData home =
      IconData(0xe909, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData shopCart =
      IconData(0xe904, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData arrowLeft =
      IconData(0xe902, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData category =
      IconData(0xe905, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData more =
      IconData(0xe90f, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData scancode =
      IconData(0xe911, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData service =
      IconData(0xe90a, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData online =
      IconData(0xe913, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData message =
      IconData(0xe90c, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData tabShopCart =
      IconData(0xe904, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData search =
      IconData(0xe912, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData logo =
      IconData(0xe915, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData qrcode =
      IconData(0xe910, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData location =
      IconData(0xe90b, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData safe =
      IconData(0xe917, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData arrowRight =
      IconData(0xe903, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData warningCircle =
      IconData(0xe914, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData close =
      IconData(0xe908, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData cny =
      IconData(0xe906, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData add =
      IconData(0xe901, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData minus =
      IconData(0xe90e, fontFamily: "xmshopIcon", matchTextDirection: true);
  static const IconData checked =
      IconData(0xe916, fontFamily: "xmshopIcon", matchTextDirection: true);
}
