server:
  port: 8732
  servlet:
    context-path: /api

spring:
  profiles:
    active: prod
    include: service
  application:
    name: xmshop
  webflux:
    base-path: /xmshop
  mvc:
    problemdetails:
      enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/xmshop?serverTimezone=UTC
    username: xmshop
    password: xmshop